// content.js - English Study Club Content Script
//
// 选区交互：
//   - 选中「单个英文单词」→ 浮动按钮显示「查词」，点击打开查词弹层
//     （释义来自 ESCTranslate：A=魔塔AI / B=本地词库；可加入网页端/插件生词本）
//   - 选中「较长文本」→ 浮动按钮显示「保存到英研社」，点击打开原保存弹层
//
// 与网页端自动 companion 通信：通过 window.postMessage 调用 browser-companion.js，
// 让插件能看到网页端生词本并实时加词（网页未打开时回退到插件本地存储）。

// ============================================================
// Local time helpers
// ============================================================
function pad2(n) {
  return n < 10 ? '0' + n : '' + n;
}
function formatLocalDateTime(d) {
  return d.getFullYear() + '-' + pad2(d.getMonth() + 1) + '-' + pad2(d.getDate()) +
    ' ' + pad2(d.getHours()) + ':' + pad2(d.getMinutes()) + ':' + pad2(d.getSeconds());
}
function formatLocalFileStamp(d) {
  return d.getFullYear() + pad2(d.getMonth() + 1) + pad2(d.getDate()) +
    '_' + pad2(d.getHours()) + pad2(d.getMinutes()) + pad2(d.getSeconds());
}

// ============================================================
// 接收网页端本地文件夹连接状态广播（core/local_file_storage.js 发出）
// 仅含文件夹名，不含句柄。存入 chrome.storage.session 供 popup 读取，
// 实现「网页端已选文件夹 → 插件显示已对齐」的感知。
// ============================================================
window.addEventListener('message', (event) => {
  try {
    const data = event.data;
    if (!data || data.source !== 'esc-web-folder') return;
    chrome.storage.session.set({
      escWebFolder: { active: !!data.active, name: data.name || '' }
    });
  } catch (e) { /* ignore */ }
});

// content script 注入后立即请求页面重发一次文件夹状态，
// 覆盖「页面 init 广播早于本监听注册」的漏广播时序问题。
try {
  window.postMessage({ source: 'esc-web-req-folder' }, '*');
} catch (e) { /* ignore */ }

// 响应 popup 的「请让网页端重发文件夹状态」请求（popup 打开时主动触发）
try {
  chrome.runtime.onMessage.addListener((msg, sender, sendResponse) => {
    if (msg && msg.action === 'requestWebFolderState') {
      try {
        window.postMessage({ source: 'esc-web-req-folder' }, '*');
      } catch (e) { /* ignore */ }
      // 主动读一次当前已存的 web 状态并回传给 popup（避免 popup 还需等延迟）
      chrome.storage.session.get('escWebFolder', (s) => {
        sendResponse({ escWebFolder: s && s.escWebFolder ? s.escWebFolder : null });
      });
      return true; // 异步 sendResponse
    }
  });
} catch (e) { /* ignore */ }

// ============================================================
// YouTube Caption Detection & Extraction
// ============================================================
function detectYouTubeCaptions() {
  try {
    const playerResponse = window.ytInitialPlayerResponse;
    if (!playerResponse || !playerResponse.captions) {
      return { success: false, error: 'No captions data found' };
    }
    const captionTracks = playerResponse.captions.playerCaptionsTracklistRenderer;
    if (!captionTracks || !captionTracks.captionTracks) {
      return { success: false, error: 'No caption tracks available' };
    }
    const tracks = captionTracks.captionTracks.map(track => ({
      name: track.name ? track.name.simpleText || track.name : 'Unknown',
      code: track.languageCode,
      url: track.baseUrl,
      kind: track.kind || '',
      autoGenerated: track.kind === 'asr' || (track.name && track.name.simpleText && track.name.simpleText.includes('auto'))
    }));
    return { success: true, tracks: tracks };
  } catch (err) {
    return { success: false, error: err.message };
  }
}

async function extractYouTubeCaptions(track) {
  try {
    const response = await fetch(track.url);
    const xmlText = await response.text();
    const parser = new DOMParser();
    const xmlDoc = parser.parseFromString(xmlText, 'text/xml');
    if (xmlDoc.querySelector('parsererror')) {
      return { success: false, error: 'Failed to parse caption XML' };
    }
    const texts = xmlDoc.querySelectorAll('text');
    const lines = [];
    texts.forEach(el => {
      const text = el.textContent || '';
      const cleaned = text.replace(/<[^>]+>/g, '').replace(/&#39;/g, "'").replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"').trim();
      if (cleaned) lines.push(cleaned);
    });
    const fullText = lines.join('\n');
    let videoTitle = '';
    try {
      const pr = window.ytInitialPlayerResponse;
      if (pr && pr.videoDetails) videoTitle = pr.videoDetails.title || '';
    } catch (e) { /* ignore */ }
    if (!videoTitle) videoTitle = document.title.replace(' - YouTube', '').trim();
    return { success: true, text: fullText, videoTitle: videoTitle, url: track.url, capturedAt: formatLocalDateTime(new Date()) };
  } catch (err) {
    return { success: false, error: err.message };
  }
}

// ============================================================
// 网页端 companion 通信（postMessage 协议）
// ============================================================
const ESC_COMPANION = (function () {
  let reqSeq = 0;
  const pending = {};
  let ready = false;

  function onMessage(ev) {
    const msg = ev.data;
    if (!msg || msg.source !== 'esc-web-companion') return;
    if (msg.type === 'esc_ready') { ready = true; return; }
    if (msg.type === 'esc_response' && pending[msg.reqId]) {
      const cb = pending[msg.reqId];
      delete pending[msg.reqId];
      cb(msg);
    }
  }

  function init() {
    window.addEventListener('message', onMessage);
  }

  // 发送请求并等待响应（带超时）
  function request(action, payload, timeout = 4000) {
    return new Promise((resolve) => {
      const reqId = 'esc' + (++reqSeq) + '_' + Date.now();
      const timer = setTimeout(() => {
        if (pending[reqId]) { delete pending[reqId]; resolve({ ok: false, error: '网页端未响应（companion 未就绪）', timeout: true }); }
      }, timeout);
      pending[reqId] = (res) => { clearTimeout(timer); resolve(res); };
      window.postMessage({ source: 'esc-browser-ext', type: 'esc_request', action: action, reqId: reqId, payload: payload || {} }, '*');
    });
  }

  return {
    init,
    isReady: () => ready,
    getNotebooks: () => request('esc_getNotebooks'),
    createNotebook: (name) => request('esc_createNotebook', { name }),
    addWord: (notebookId, wordData) => request('esc_addWord', { notebookId, wordData }),
    getApiConfig: () => request('esc_getApiConfig'),
  };
})();

// 暴露给 translate.js（同 content script 上下文内共享）
window.ESC_COMPANION = ESC_COMPANION;

// ============================================================
// Injected Styles
// ============================================================
function injectStyles() {
  if (document.getElementById('erl-styles')) return;
  const style = document.createElement('style');
  style.id = 'erl-styles';
  style.textContent = `
/* ===== Floating button ===== */
#erl-floating-btn {
  position: fixed;
  z-index: 2147483647;
  display: none;
  align-items: center;
  gap: 6px;
  padding: 8px 16px;
  border-radius: 999px;
  background: #506080;
  color: #ffffff;
  font-size: 13px;
  font-weight: 500;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  cursor: pointer;
  box-shadow: 0 4px 12px rgba(0,0,0,0.15);
  transition: background 150ms ease, transform 150ms ease, opacity 150ms ease;
  opacity: 0;
  transform: translateY(4px);
  pointer-events: none;
  user-select: none;
  white-space: nowrap;
  line-height: 1;
}
#erl-floating-btn.show { display: flex; opacity: 1; transform: translateY(0); pointer-events: auto; }
#erl-floating-btn.show:hover { background: #445271; transform: translateY(-1px); }
#erl-floating-btn svg { flex-shrink: 0; }

/* ===== 通用弹层 ===== */
.erl-modal-mask { position: fixed; z-index: 2147483646; inset: 0; display: none; }
.erl-modal-mask.show { display: block; }
.erl-modal-overlay { position: absolute; inset: 0; background: rgba(15,23,42,0.4); }
.erl-modal-box {
  position: absolute;
  top: 50%; left: 50%;
  transform: translate(-50%, -50%) scale(0.96);
  opacity: 0;
  transition: transform 160ms cubic-bezier(.16,1,.3,1), opacity 160ms ease;
  background: #ffffff;
  border-radius: 16px;
  width: 440px;
  max-width: 92vw;
  box-shadow: 0 16px 48px rgba(0,0,0,0.18);
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  font-size: 14px;
  color: #1e293b;
}
.erl-modal-mask.show .erl-modal-box { transform: translate(-50%, -50%) scale(1); opacity: 1; }
.erl-modal-header { display: flex; align-items: center; justify-content: space-between; padding: 16px 20px; border-bottom: 1px solid #eef1f5; }
.erl-modal-title { font-weight: 600; font-size: 15px; color: #1e293b; }
.erl-modal-close { display: inline-flex; align-items: center; justify-content: center; width: 28px; height: 28px; padding: 0; background: none; border: none; border-radius: 6px; color: #94a3b8; cursor: pointer; }
.erl-modal-close:hover { color: #475569; background: #f8fafc; }
.erl-modal-body { padding: 20px; }
.erl-modal-footer { display: flex; justify-content: flex-end; gap: 8px; padding: 12px 20px; border-top: 1px solid #eef1f5; }
.erl-btn { padding: 8px 16px; border-radius: 8px; font-size: 13px; cursor: pointer; transition: background 150ms ease, filter 150ms ease; }
.erl-btn-cancel { border: 1px solid #e2e8f0; background: #ffffff; color: #64748b; }
.erl-btn-cancel:hover { background: #f8fafc; }
.erl-btn-primary { border: none; background: #506080; color: #ffffff; font-weight: 500; }
.erl-btn-primary:hover { background: #445271; }
.erl-btn-primary:active { filter: brightness(0.94); }
.erl-btn-primary:disabled { opacity: 0.5; cursor: not-allowed; }

/* 划线保存预览 */
.erl-preview { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 12px; font-size: 13px; line-height: 1.6; max-height: 150px; overflow-y: auto; margin-bottom: 16px; color: #64748b; white-space: pre-wrap; word-break: break-word; }
.erl-input { width: 100%; padding: 8px 12px; margin-top: 6px; border: 1px solid #e2e8f0; border-radius: 8px; font-size: 13px; color: #1e293b; outline: none; box-sizing: border-box; }
.erl-input:focus { border-color: #506080; box-shadow: 0 0 0 3px rgba(80,96,128,0.15); }
.erl-label { font-size: 13px; font-weight: 500; color: #64748b; }

/* ===== 查词弹层 ===== */
#erl-lookup-word { font-size: 22px; font-weight: 700; color: #1e293b; display: flex; align-items: baseline; gap: 10px; }
#erl-lookup-phonetic { font-size: 14px; font-weight: 400; color: #94a3b8; }
#erl-lookup-pos { font-size: 12px; color: #E07B5A; font-weight: 600; margin: 6px 0 2px; }
#erl-lookup-def { font-size: 15px; color: #334155; line-height: 1.5; }
#erl-lookup-ex { font-size: 13px; color: #64748b; font-style: italic; margin-top: 8px; border-left: 3px solid #e2e8f0; padding-left: 10px; }
.erl-lookup-meta { font-size: 12px; color: #94a3b8; margin-top: 4px; }
.erl-loading { color: #94a3b8; font-size: 13px; padding: 10px 0; }
.erl-target-row { display: flex; align-items: center; gap: 8px; margin-top: 14px; }
.erl-target-row select { flex: 1; }
.erl-status { font-size: 12px; margin-top: 10px; min-height: 16px; }
.erl-status.ok { color: #10B981; }
.erl-status.err { color: #EF4444; }
.erl-status.warn { color: #F59E0B; }
.erl-newbook { margin-top: 8px; display: none; }
.erl-newbook.show { display: block; }
`;
  document.head.appendChild(style);
}

// ============================================================
// 选区 / 浮动按钮 / 弹层
// ============================================================
let floatingBtn = null;
let saveModal = null;
let lookupModal = null;
let currentSelection = null;     // { text, isWord }
let lookupResult = null;         // 最近一次查词结果

const WORD_RE = /^[a-zA-Z][a-zA-Z'\-]*$/;

function isSingleWord(text) {
  const t = (text || '').trim();
  return t.length > 0 && t.length <= 40 && WORD_RE.test(t);
}

function createFloatingButton() {
  if (floatingBtn) return;
  injectStyles();
  floatingBtn = document.createElement('div');
  floatingBtn.id = 'erl-floating-btn';
  floatingBtn.setAttribute('role', 'button');
  floatingBtn.innerHTML =
    '<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"></path><path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z"></path></svg>' +
    '<span class="erl-btn-text">保存</span>';
  floatingBtn.addEventListener('click', (e) => {
    e.preventDefault(); e.stopPropagation();
    if (currentSelection && currentSelection.isWord) openLookupModal(currentSelection.text);
    else showSaveModal();
  });
  document.body.appendChild(floatingBtn);
}

function createSaveModal() {
  if (saveModal) return;
  injectStyles();
  saveModal = document.createElement('div');
  saveModal.className = 'erl-modal-mask';
  saveModal.id = 'erl-save-modal';
  saveModal.innerHTML = [
    '<div class="erl-modal-overlay"></div>',
    '<div class="erl-modal-box">',
    '  <div class="erl-modal-header"><span class="erl-modal-title">保存选中文本</span>',
    '    <button class="erl-modal-close" aria-label="关闭"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg></button>',
    '  </div>',
    '  <div class="erl-modal-body">',
    '    <div class="erl-preview"></div>',
    '    <label class="erl-label" for="erl-save-tag">标签/备注 (可选)</label>',
    '    <input type="text" class="erl-input erl-save-tag" placeholder="输入标签或备注...">',
    '  </div>',
    '  <div class="erl-modal-footer"><button class="erl-btn erl-btn-cancel">取消</button><button class="erl-btn erl-btn-primary erl-save-go">保存</button></div>',
    '</div>'
  ].join('');
  document.body.appendChild(saveModal);
  saveModal.querySelector('.erl-modal-close').addEventListener('click', hideSaveModal);
  saveModal.querySelector('.erl-modal-overlay').addEventListener('click', hideSaveModal);
  saveModal.querySelector('.erl-btn-cancel').addEventListener('click', hideSaveModal);
  saveModal.querySelector('.erl-save-go').addEventListener('click', saveSelection);
}

function showSaveModal() {
  if (!saveModal) createSaveModal();
  if (!currentSelection) return;
  const text = currentSelection.text;
  saveModal.querySelector('.erl-preview').textContent = text.length > 200 ? text.slice(0, 200) + '...' : text;
  saveModal.querySelector('.erl-save-tag').value = '';
  saveModal.querySelector('.erl-save-go').disabled = false;
  saveModal.classList.add('show');
  hideFloatingButton();
}
function hideSaveModal() { if (saveModal) saveModal.classList.remove('show'); }

// ---------- 查词弹层 ----------
function createLookupModal() {
  if (lookupModal) return;
  injectStyles();
  lookupModal = document.createElement('div');
  lookupModal.className = 'erl-modal-mask';
  lookupModal.id = 'erl-lookup-modal';
  lookupModal.innerHTML = [
    '<div class="erl-modal-overlay"></div>',
    '<div class="erl-modal-box">',
    '  <div class="erl-modal-header"><span class="erl-modal-title">查词</span>',
    '    <button class="erl-modal-close" aria-label="关闭"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg></button>',
    '  </div>',
    '  <div class="erl-modal-body">',
    '    <div id="erl-lookup-word"></div>',
    '    <div id="erl-lookup-pos"></div>',
    '    <div id="erl-lookup-def"></div>',
    '    <div id="erl-lookup-ex"></div>',
    '    <div class="erl-lookup-meta"></div>',
    '    <div class="erl-target-row">',
    '      <select class="erl-input erl-notebook-select"><option value="">加载生词本…</option></select>',
    '      <button class="erl-btn erl-btn-cancel erl-newbook-btn" title="新建生词本">+</button>',
    '    </div>',
    '    <div class="erl-newbook"><input type="text" class="erl-input erl-newbook-input" placeholder="生词本名称…"></button></div>',
    '    <div class="erl-status"></div>',
    '  </div>',
    '  <div class="erl-modal-footer"><button class="erl-btn erl-btn-cancel erl-lookup-cancel">关闭</button><button class="erl-btn erl-btn-primary erl-lookup-add">加入生词本</button></div>',
    '</div>'
  ].join('');
  document.body.appendChild(lookupModal);
  lookupModal.querySelector('.erl-modal-close').addEventListener('click', hideLookupModal);
  lookupModal.querySelector('.erl-modal-overlay').addEventListener('click', hideLookupModal);
  lookupModal.querySelector('.erl-lookup-cancel').addEventListener('click', hideLookupModal);
  lookupModal.querySelector('.erl-lookup-add').addEventListener('click', addLookupWord);
  lookupModal.querySelector('.erl-newbook-btn').addEventListener('click', onNewNotebook);
}

async function openLookupModal(word) {
  if (!lookupModal) createLookupModal();
  lookupModal.classList.add('show');
  hideFloatingButton();
  const wEl = document.getElementById('erl-lookup-word');
  const posEl = document.getElementById('erl-lookup-pos');
  const defEl = document.getElementById('erl-lookup-def');
  const exEl = document.getElementById('erl-lookup-ex');
  const metaEl = document.querySelector('#erl-lookup-modal .erl-lookup-meta');
  const statusEl = lookupModal.querySelector('.erl-status');
  wEl.innerHTML = '<span>' + escapeHtml(word) + '</span>';
  posEl.textContent = ''; defEl.textContent = ''; exEl.textContent = ''; metaEl.textContent = '';
  statusEl.className = 'erl-status'; statusEl.textContent = '';
  defEl.className = 'erl-loading'; defEl.textContent = '查词中…';
  lookupModal.querySelector('.erl-lookup-add').disabled = true;

  const settings = await window.ESCStore.getSettings();
  let res;
  try {
    res = await window.ESCTranslate.lookup(word, { settings });
  } catch (e) {
    res = { word: word, phonetic: '', pos: '', definition: '查词失败：' + (e.message || e), example: '', source: '?' };
  }
  lookupResult = res;
  defEl.className = 'erl-lookup-def';
  wEl.innerHTML = '<span>' + escapeHtml(res.word || word) + '</span>' +
    (res.phonetic ? '<span id="erl-lookup-phonetic">/' + escapeHtml(res.phonetic) + '/</span>' : '');
  posEl.textContent = res.pos || '';
  defEl.textContent = res.definition || '（无释义）';
  exEl.textContent = res.example || '';
  metaEl.textContent = '来源：' + sourceLabel(res.source) + (res.source === 'A' ? '（魔塔 AI）' : '（本地词库）');
  lookupModal.querySelector('.erl-lookup-add').disabled = false;

  // 加载生词本列表（优先网页端 companion，回退本地）
  await loadNotebookOptions();
}

function sourceLabel(s) {
  if (s === 'A') return '魔塔 AI';
  if (s === 'B') return '本地词库';
  if (s && s.indexOf('降级') >= 0) return '本地词库（降级）';
  return s || '—';
}

function hideLookupModal() { if (lookupModal) lookupModal.classList.remove('show'); }

// 加载笔记本下拉：先问网页端 companion，失败/超时回退插件本地
async function loadNotebookOptions() {
  const sel = lookupModal.querySelector('.erl-notebook-select');
  sel.innerHTML = '<option value="">加载生词本…</option>';
  let webNotebooks = [];
  try {
    const r = await ESC_COMPANION.getNotebooks();
    if (r && r.ok && r.data && r.data.notebooks) {
      webNotebooks = r.data.notebooks;
    }
  } catch (e) { /* 忽略，走本地回退 */ }

  if (webNotebooks.length > 0) {
    sel.innerHTML = '';
    const hint = document.createElement('option');
    hint.disabled = true; hint.textContent = '— 网页端生词本 —';
    sel.appendChild(hint);
    webNotebooks.forEach(function (nb) {
      const o = document.createElement('option');
      o.value = 'web:' + nb.id;
      o.textContent = nb.name + '（' + nb.count + '）';
      sel.appendChild(o);
    });
    const o2 = document.createElement('option');
    o2.value = 'local:__esc_local__';
    o2.textContent = '— 仅存浏览器插件 —';
    sel.appendChild(o2);
  } else {
    sel.innerHTML = '<option value="local:__esc_local__">浏览器插件生词本（网页端未打开）</option>';
  }
}

function onNewNotebook() {
  const box = lookupModal.querySelector('.erl-newbook');
  box.classList.toggle('show');
  if (box.classList.contains('show')) {
    const input = lookupModal.querySelector('.erl-newbook-input');
    input.focus();
    input.onkeydown = function (e) {
      if (e.key === 'Enter') createNewNotebookFromLookup();
    };
  }
}

async function createNewNotebookFromLookup() {
  const input = lookupModal.querySelector('.erl-newbook-input');
  const name = (input.value || '').trim();
  if (!name) return;
  const statusEl = lookupModal.querySelector('.erl-status');
  statusEl.className = 'erl-status'; statusEl.textContent = '新建中…';
  try {
    const r = await ESC_COMPANION.createNotebook(name);
    if (r && r.ok && r.data && r.data.id) {
      await loadNotebookOptions();
      const sel = lookupModal.querySelector('.erl-notebook-select');
      sel.value = 'web:' + r.data.id;
      statusEl.className = 'erl-status ok'; statusEl.textContent = '已新建《' + name + '》';
      lookupModal.querySelector('.erl-newbook').classList.remove('show');
      input.value = '';
      return;
    }
    statusEl.className = 'erl-status warn'; statusEl.textContent = (r && r.error) ? ('新建失败：' + r.error) : '网页端未打开，已存为插件生词本';
    // 回退：以插件本地存储记录（用 notebook 名）
    const sel = lookupModal.querySelector('.erl-notebook-select');
    sel.innerHTML = '<option value="local:__esc_local__">浏览器插件生词本（网页端未打开）</option>';
    sel.value = 'local:__esc_local__';
  } catch (e) {
    statusEl.className = 'erl-status warn'; statusEl.textContent = '网页端未响应，将存为插件生词本';
  }
}

async function addLookupWord() {
  if (!lookupResult) return;
  const sel = lookupModal.querySelector('.erl-notebook-select');
  const val = sel.value || 'local:__esc_local__';
  const statusEl = lookupModal.querySelector('.erl-status');
  const addBtn = lookupModal.querySelector('.erl-lookup-add');
  addBtn.disabled = true;

  const wordData = {
    word: lookupResult.word,
    phonetic: lookupResult.phonetic || '',
    definition: lookupResult.definition || '',
    example: lookupResult.example || '',
    pos: lookupResult.pos || '',
    context: '',
    timestamp: Date.now(),
  };

  // 1) 尝试实时写入网页端（companion）
  if (val.indexOf('web:') === 0) {
    const nbId = val.slice(4);
    const nbName = sel.options[sel.selectedIndex] ? sel.options[sel.selectedIndex].textContent.split('（')[0] : '网页端';
    statusEl.className = 'erl-status'; statusEl.textContent = '正在加入《' + nbName + '》…';
    const r = await ESC_COMPANION.addWord(nbId, wordData);
    if (r && r.ok) {
      statusEl.className = 'erl-status ok';
      statusEl.textContent = '已加入网页端《' + nbName + '》';
      setTimeout(hideLookupModal, 700);
      addBtn.disabled = false;
      return;
    }
    // 失败：回退存插件本地
    await window.ESCStore.addVocab(Object.assign({}, wordData, { notebook: nbName }));
    statusEl.className = 'erl-status warn';
    statusEl.textContent = '网页端未响应，已存入浏览器插件生词本《' + nbName + '》';
    setTimeout(hideLookupModal, 900);
    addBtn.disabled = false;
    return;
  }

  // 2) 仅存浏览器插件本地
  await window.ESCStore.addVocab(Object.assign({}, wordData, { notebook: 'default' }));
  statusEl.className = 'erl-status ok';
  statusEl.textContent = '已存入浏览器插件生词本';
  setTimeout(hideLookupModal, 700);
  addBtn.disabled = false;
}

function escapeHtml(s) {
  return String(s == null ? '' : s)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;').replace(/'/g, '&#39;');
}

// ---------- 划线保存 ----------
function buildArticleMd(time, tag, text) {
  return [
    '# ' + (document.title || ''),
    '',
    '- 来源: ' + window.location.href,
    '- 保存时间: ' + formatLocalDateTime(time),
    '- 标签: ' + (tag || ''),
    '',
    '> ' + text
  ].join('\n');
}

async function saveSelection() {
  if (!currentSelection) return;
  const saveBtn = saveModal.querySelector('.erl-save-go');
  const tag = saveModal.querySelector('.erl-save-tag').value.trim();
  saveBtn.disabled = true; saveBtn.textContent = '保存中...';
  try {
    const now = new Date();
    const stamp = formatLocalFileStamp(now);
    const filename = 'article_' + stamp + '.md';
    const content = buildArticleMd(now, tag, currentSelection.text);
    if (window.ESCStore) {
      await window.ESCStore.addCapture({
        id: 'cap_' + stamp,
        title: document.title || '网页采集',
        text: currentSelection.text,
        url: window.location.href,
        source: 'selection',
        createdAt: window.ESCStore.nowIso(),
      });
    }
    // 优先写入已选定的本地文件夹；未选定或失败则回退下载兜底。
    const written = await writeToFolder(filename, content);

    if (!written) {
      // 回退：下载兜底（仅当未选定文件夹时主动触发；选定但写入失败也兜底）
      try {
        const now = new Date();
        downloadFallback('article_' + formatLocalFileStamp(now) + '.md', content, 'text/markdown;charset=utf-8');
      } catch (dlErr) { /* 下载失败不阻断本地存储 */ }
    }
    hideSaveModal();
    currentSelection = null;
  } catch (err) {
    try {
      const now = new Date();
      downloadFallback('article_' + formatLocalFileStamp(now) + '.md', buildArticleMd(now, tag, currentSelection.text), 'text/markdown;charset=utf-8');
      hideSaveModal();
      currentSelection = null;
    } catch (e2) {
      alert('保存失败: ' + err.message);
    }
  } finally {
    saveBtn.disabled = false; saveBtn.textContent = '保存';
  }
}

// 保留兼容：native host 已废弃，恒为 false
async function checkNativeHost() {
  return false;
}

// ============================================================
// 本地文件夹缓存（File System Access API）
// 在页面内触发 showDirectoryPicker，把 DirectoryHandle 存入
// chrome.storage.session（结构化克隆可存 FileSystemHandle）。
// 之后采集/字幕优先写入该文件夹，失败回退 chrome.storage.local + 下载。
// ============================================================
async function getFolderHandle() {
  try {
    const s = await chrome.storage.session.get('escFolder');
    if (s.escFolder && s.escFolder.handle) {
      // 跨页面/跨时间权限可能失效，先验证
      try {
        const perm = await s.escFolder.handle.queryPermission({ mode: 'readwrite' });
        if (perm !== 'granted') {
          const req = await s.escFolder.handle.requestPermission({ mode: 'readwrite' });
          if (req !== 'granted') return null;
        }
        return s.escFolder.handle;
      } catch (e) { return null; }
    }
  } catch (e) { /* ignore */ }
  return null;
}

// 写入本地文件夹。成功返回 true；无文件夹或失败返回 false（调用方需回退）。
async function writeToFolder(filename, content) {
  const handle = await getFolderHandle();
  if (!handle) return false;
  try {
    const fileHandle = await handle.getFileHandle(filename, { create: true });
    const writable = await fileHandle.createWritable();
    await writable.write(content);
    await writable.close();
    return true;
  } catch (e) {
    return false;
  }
}

function downloadFallback(filename, content, mimeType) {
  const blob = new Blob([content], { type: mimeType || 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename;
  document.body.appendChild(a); a.click(); document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// ---------- 浮动按钮显示 ----------
function hideFloatingButton() { if (floatingBtn) floatingBtn.classList.remove('show'); }
function showFloatingButton(x, y) {
  if (!floatingBtn) createFloatingButton();
  const btnWidth = 140, btnHeight = 36, margin = 10;
  let left = x + margin, top = y - btnHeight - margin;
  if (left + btnWidth > window.innerWidth - 10) left = window.innerWidth - btnWidth - 10;
  if (top < 10) top = y + margin;
  if (left < 10) left = 10;
  floatingBtn.style.left = left + 'px';
  floatingBtn.style.top = top + 'px';
  floatingBtn.classList.add('show');
}

// ============================================================
// Selection handlers
// ============================================================
document.addEventListener('mouseup', (e) => {
  setTimeout(() => {
    const selection = window.getSelection();
    if (!selection || selection.isCollapsed || !selection.toString().trim()) {
      if (!e.target.closest('#erl-floating-btn') && !e.target.closest('.erl-modal-mask')) {
        hideFloatingButton();
        currentSelection = null;
      }
      return;
    }
    const text = selection.toString().trim();
    if (!text) return;
    const asWord = isSingleWord(text);
    currentSelection = { text: text, isWord: asWord };
    const txtEl = floatingBtn.querySelector('.erl-btn-text');
    if (txtEl) txtEl.textContent = asWord ? '查词' : '保存到英研社';
    const range = selection.getRangeAt(0);
    const rect = range.getBoundingClientRect();
    showFloatingButton(rect.left + rect.width / 2, rect.top + window.scrollY);
  }, 10);
});

document.addEventListener('mousedown', (e) => {
  if (!e.target.closest('#erl-floating-btn') && !e.target.closest('.erl-modal-mask')) {
    const selection = window.getSelection();
    if (!selection || selection.isCollapsed) hideFloatingButton();
  }
});

// ============================================================
// Message Listener
// ============================================================
chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  if (request.action === 'detectCaptions') { sendResponse(detectYouTubeCaptions()); return true; }
  if (request.action === 'extractCaptions') {
    extractYouTubeCaptions(request.track).then(result => sendResponse(result));
    return true;
  }
  if (request.action === 'getSelectionStatus') {
    const selection = window.getSelection();
    sendResponse({ hasSelection: !!(selection && !selection.isCollapsed && selection.toString().trim().length > 0) });
    return true;
  }
});

// ============================================================
// Init
// ============================================================
(function init() {
  ESC_COMPANION.init();
  createFloatingButton();
  createSaveModal();
  createLookupModal();
})();
