// content.js - English Reading Lab Content Script

// ============================================================
// Local time helpers (本地时间，不使用 toISOString 避免时区偏差)
// ============================================================

function pad2(n) {
  return n < 10 ? '0' + n : '' + n;
}

// 本地时间 → YYYY-MM-DD HH:mm:ss
function formatLocalDateTime(d) {
  return d.getFullYear() + '-' + pad2(d.getMonth() + 1) + '-' + pad2(d.getDate()) +
    ' ' + pad2(d.getHours()) + ':' + pad2(d.getMinutes()) + ':' + pad2(d.getSeconds());
}

// 本地时间 → YYYYMMDD_HHmmss（用于文件名）
function formatLocalFileStamp(d) {
  return d.getFullYear() + pad2(d.getMonth() + 1) + pad2(d.getDate()) +
    '_' + pad2(d.getHours()) + pad2(d.getMinutes()) + pad2(d.getSeconds());
}

// ============================================================
// YouTube Caption Detection & Extraction
// ============================================================

function detectYouTubeCaptions() {
  try {
    const playerResponse = window.ytInitialPlayerResponse;
    if (!playerResponse || !playerResponse.captions) {
      return { success: false, error: 'No captions data found' };
    }

    const captionTracks = playerResponse.captions.playerCaptionsTracklistRenderer;
    if (!captionTracks || !captionTracks.captionTracks) {
      return { success: false, error: 'No caption tracks available' };
    }

    const tracks = captionTracks.captionTracks.map(track => ({
      name: track.name ? track.name.simpleText || track.name : 'Unknown',
      code: track.languageCode,
      url: track.baseUrl,
      kind: track.kind || '',
      autoGenerated: track.kind === 'asr' || (track.name && track.name.simpleText && track.name.simpleText.includes('auto'))
    }));

    return { success: true, tracks: tracks };
  } catch (err) {
    return { success: false, error: err.message };
  }
}

async function extractYouTubeCaptions(track) {
  try {
    const response = await fetch(track.url);
    const xmlText = await response.text();

    const parser = new DOMParser();
    const xmlDoc = parser.parseFromString(xmlText, 'text/xml');

    if (xmlDoc.querySelector('parsererror')) {
      return { success: false, error: 'Failed to parse caption XML' };
    }

    const texts = xmlDoc.querySelectorAll('text');
    const lines = [];
    texts.forEach(el => {
      const text = el.textContent || '';
      const cleaned = text.replace(/<[^>]+>/g, '').replace(/&#39;/g, "'").replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"').trim();
      if (cleaned) {
        lines.push(cleaned);
      }
    });

    const fullText = lines.join('\n');

    let videoTitle = '';
    try {
      const playerResponse = window.ytInitialPlayerResponse;
      if (playerResponse && playerResponse.videoDetails) {
        videoTitle = playerResponse.videoDetails.title || '';
      }
    } catch (e) { /* ignore */ }

    if (!videoTitle) {
      videoTitle = document.title.replace(' - YouTube', '').trim();
    }

    // 返回结构约定：popup 端负责组装 MD（含 # 标题、- 来源、- 提取时间、正文）
    return {
      success: true,
      text: fullText,
      videoTitle: videoTitle,
      url: track.url,
      capturedAt: formatLocalDateTime(new Date())
    };
  } catch (err) {
    return { success: false, error: err.message };
  }
}

// ============================================================
// Injected Styles (单一 <style> 标签，全部使用十六进制色值，
// 不依赖宿主页 CSS 变量)
// ============================================================

function injectStyles() {
  if (document.getElementById('erl-styles')) return;

  const style = document.createElement('style');
  style.id = 'erl-styles';
  style.textContent = `
/* ===== Floating button ===== */
#erl-floating-btn {
  position: fixed;
  z-index: 2147483647;
  display: none;
  align-items: center;
  gap: 6px;
  padding: 8px 16px;
  border-radius: 999px;
  background: #3b82f6;
  color: #ffffff;
  font-size: 13px;
  font-weight: 500;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  cursor: pointer;
  box-shadow: 0 4px 12px rgba(0,0,0,0.15);
  transition: background 150ms ease, transform 150ms ease, opacity 150ms ease;
  opacity: 0;
  transform: translateY(4px);
  pointer-events: none;
  user-select: none;
  white-space: nowrap;
  line-height: 1;
}
#erl-floating-btn.show {
  display: flex;
  opacity: 1;
  transform: translateY(0);
  pointer-events: auto;
}
#erl-floating-btn.show:hover {
  background: #2563eb;
  transform: translateY(-1px);
}
#erl-floating-btn svg {
  flex-shrink: 0;
}

/* ===== Selection modal ===== */
#erl-selection-modal { position: fixed; z-index: 2147483646; inset: 0; display: none; }
#erl-selection-modal.show { display: block; }
#erl-modal-overlay { position: absolute; inset: 0; background: rgba(15,23,42,0.4); }
#erl-modal-box {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%) scale(0.96);
  opacity: 0;
  transition: transform 150ms ease, opacity 150ms ease;
  background: #ffffff;
  border-radius: 14px;
  width: 420px;
  max-width: 90vw;
  box-shadow: 0 16px 40px rgba(0,0,0,0.15);
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  font-size: 14px;
  color: #1e293b;
}
#erl-selection-modal.show #erl-modal-box {
  transform: translate(-50%, -50%) scale(1);
  opacity: 1;
}
#erl-modal-header { display: flex; align-items: center; justify-content: space-between; padding: 16px 20px; border-bottom: 1px solid #e2e8f0; }
#erl-modal-title { font-weight: 600; font-size: 15px; color: #1e293b; }
#erl-modal-close {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 28px;
  height: 28px;
  padding: 0;
  background: none;
  border: none;
  border-radius: 6px;
  color: #94a3b8;
  cursor: pointer;
}
#erl-modal-close:hover { color: #475569; background: #f8fafc; }
#erl-modal-body { padding: 20px; }
#erl-modal-body label { font-size: 13px; font-weight: 500; color: #64748b; }
#erl-modal-preview {
  background: #f8fafc;
  border: 1px solid #e2e8f0;
  border-radius: 8px;
  padding: 12px;
  font-size: 13px;
  line-height: 1.6;
  max-height: 150px;
  overflow-y: auto;
  margin-bottom: 16px;
  color: #64748b;
  white-space: pre-wrap;
  word-break: break-word;
}
#erl-modal-tag {
  width: 100%;
  padding: 8px 12px;
  margin-top: 6px;
  border: 1px solid #e2e8f0;
  border-radius: 6px;
  font-size: 13px;
  color: #1e293b;
  outline: none;
  box-sizing: border-box;
}
#erl-modal-tag:focus {
  border-color: #3b82f6;
  box-shadow: 0 0 0 3px rgba(59,130,246,0.15);
}
#erl-modal-footer { display: flex; justify-content: flex-end; gap: 8px; padding: 12px 20px; border-top: 1px solid #e2e8f0; }
#erl-modal-cancel {
  padding: 8px 16px;
  border: 1px solid #e2e8f0;
  border-radius: 6px;
  background: #ffffff;
  color: #64748b;
  font-size: 13px;
  cursor: pointer;
  transition: background 150ms ease;
}
#erl-modal-cancel:hover { background: #f8fafc; }
#erl-modal-cancel:active { background: #e2e8f0; }
#erl-modal-save {
  padding: 8px 16px;
  border: none;
  border-radius: 6px;
  background: #3b82f6;
  color: #ffffff;
  font-size: 13px;
  font-weight: 500;
  cursor: pointer;
  transition: background 150ms ease;
}
#erl-modal-save:hover { background: #2563eb; }
#erl-modal-save:active { background: #2563eb; filter: brightness(0.92); }
#erl-modal-save:disabled { opacity: 0.5; cursor: not-allowed; }
`;

  document.head.appendChild(style);
}

// ============================================================
// Text Selection & Floating Button
// ============================================================

let floatingBtn = null;
let selectionModal = null;
let currentSelection = null;

function createFloatingButton() {
  if (floatingBtn) return;
  injectStyles();

  floatingBtn = document.createElement('div');
  floatingBtn.id = 'erl-floating-btn';
  floatingBtn.setAttribute('role', 'button');
  floatingBtn.setAttribute('aria-label', '保存到阅读实验室');
  floatingBtn.innerHTML =
    '<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">' +
    '<path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"></path>' +
    '<path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z"></path>' +
    '</svg>' +
    '<span>保存到阅读实验室</span>';

  floatingBtn.addEventListener('click', (e) => {
    e.preventDefault();
    e.stopPropagation();
    showSelectionModal();
  });

  document.body.appendChild(floatingBtn);
}

function createSelectionModal() {
  if (selectionModal) return;
  injectStyles();

  selectionModal = document.createElement('div');
  selectionModal.id = 'erl-selection-modal';
  selectionModal.innerHTML = [
    '<div id="erl-modal-overlay"></div>',
    '<div id="erl-modal-box">',
    '  <div id="erl-modal-header">',
    '    <span id="erl-modal-title">保存选中文本</span>',
    '    <button id="erl-modal-close" aria-label="关闭">',
    '      <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">',
    '        <line x1="18" y1="6" x2="6" y2="18"></line>',
    '        <line x1="6" y1="6" x2="18" y2="18"></line>',
    '      </svg>',
    '    </button>',
    '  </div>',
    '  <div id="erl-modal-body">',
    '    <div id="erl-modal-preview"></div>',
    '    <label for="erl-modal-tag">标签/备注 (可选)</label>',
    '    <input type="text" id="erl-modal-tag" placeholder="输入标签或备注...">',
    '  </div>',
    '  <div id="erl-modal-footer">',
    '    <button id="erl-modal-cancel" class="erl-btn-cancel">取消</button>',
    '    <button id="erl-modal-save" class="erl-btn-save">保存</button>',
    '  </div>',
    '</div>'
  ].join('');

  document.body.appendChild(selectionModal);

  // Modal events（仅在此处绑定一次，避免重复绑定）
  document.getElementById('erl-modal-close').addEventListener('click', hideSelectionModal);
  document.getElementById('erl-modal-overlay').addEventListener('click', hideSelectionModal);
  document.getElementById('erl-modal-cancel').addEventListener('click', hideSelectionModal);
  document.getElementById('erl-modal-save').addEventListener('click', saveSelection);
}

function showSelectionModal() {
  if (!selectionModal) createSelectionModal();
  if (!currentSelection) return;

  const preview = document.getElementById('erl-modal-preview');
  const text = currentSelection.text;
  preview.textContent = text.length > 200 ? text.slice(0, 200) + '...' : text;

  document.getElementById('erl-modal-tag').value = '';
  document.getElementById('erl-modal-save').disabled = false;
  selectionModal.classList.add('show');

  hideFloatingButton();
}

function hideSelectionModal() {
  if (selectionModal) {
    selectionModal.classList.remove('show');
  }
}

function hideFloatingButton() {
  if (floatingBtn) {
    floatingBtn.classList.remove('show');
  }
}

function showFloatingButton(x, y) {
  if (!floatingBtn) createFloatingButton();

  const btnWidth = 140;
  const btnHeight = 36;
  const margin = 10;

  let left = x + margin;
  let top = y - btnHeight - margin;

  if (left + btnWidth > window.innerWidth - 10) {
    left = window.innerWidth - btnWidth - 10;
  }
  if (top < 10) {
    top = y + margin;
  }
  if (left < 10) left = 10;

  floatingBtn.style.left = left + 'px';
  floatingBtn.style.top = top + 'px';
  floatingBtn.classList.add('show');
}

// 组装文章划线保存的 Markdown 内容
function buildArticleMd(time, tag, text) {
  return [
    '# ' + (document.title || ''),
    '',
    '- 来源: ' + window.location.href,
    '- 保存时间: ' + formatLocalDateTime(time),
    '- 标签: ' + (tag || ''),
    '',
    '> ' + text
  ].join('\n');
}

async function saveSelection() {
  if (!currentSelection) return;

  const saveBtn = document.getElementById('erl-modal-save');
  const tag = document.getElementById('erl-modal-tag').value.trim();
  // 防重入：保存期间禁用按钮
  saveBtn.disabled = true;
  saveBtn.textContent = '保存中...';

  try {
    const now = new Date();
    const filename = 'article_' + formatLocalFileStamp(now) + '.md';
    const content = buildArticleMd(now, tag, currentSelection.text);

    const connected = await checkNativeHost();

    if (connected) {
      await chrome.runtime.sendMessage({
        action: 'write',
        path: 'browser-captures/' + filename,
        content: content
      });
    } else {
      downloadFallback(filename, content, 'text/markdown;charset=utf-8');
    }

    hideSelectionModal();
    currentSelection = null;
  } catch (err) {
    try {
      // Native Host 写入失败时回退为浏览器下载（同样生成 .md 文件）
      const now = new Date();
      const filename = 'article_' + formatLocalFileStamp(now) + '.md';
      downloadFallback(filename, buildArticleMd(now, tag, currentSelection.text), 'text/markdown;charset=utf-8');
      hideSelectionModal();
      currentSelection = null;
    } catch (e2) {
      alert('保存失败: ' + err.message);
    }
  } finally {
    saveBtn.disabled = false;
    saveBtn.textContent = '保存';
  }
}

async function checkNativeHost() {
  try {
    const response = await chrome.runtime.sendMessage({ action: 'ping' });
    return response && response.connected;
  } catch (e) {
    return false;
  }
}

function downloadFallback(filename, content, mimeType) {
  const blob = new Blob([content], { type: mimeType || 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// Mouseup handler for text selection
document.addEventListener('mouseup', (e) => {
  setTimeout(() => {
    const selection = window.getSelection();
    if (!selection || selection.isCollapsed || !selection.toString().trim()) {
      // Don't hide if clicking inside our own UI
      if (!e.target.closest('#erl-floating-btn') && !e.target.closest('#erl-selection-modal')) {
        hideFloatingButton();
        currentSelection = null;
      }
      return;
    }

    const text = selection.toString().trim();
    if (!text) return;

    currentSelection = { text: text };

    const range = selection.getRangeAt(0);
    const rect = range.getBoundingClientRect();
    const x = rect.left + rect.width / 2;
    const y = rect.top + window.scrollY;

    showFloatingButton(x, y);
  }, 10);
});

// Hide floating button when clicking elsewhere
document.addEventListener('mousedown', (e) => {
  if (!e.target.closest('#erl-floating-btn') && !e.target.closest('#erl-selection-modal')) {
    const selection = window.getSelection();
    if (!selection || selection.isCollapsed) {
      hideFloatingButton();
    }
  }
});

// ============================================================
// Message Listener
// ============================================================

chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  if (request.action === 'detectCaptions') {
    const result = detectYouTubeCaptions();
    sendResponse(result);
    return true;
  }

  if (request.action === 'extractCaptions') {
    extractYouTubeCaptions(request.track).then(result => {
      sendResponse(result);
    });
    return true;
  }

  if (request.action === 'getSelectionStatus') {
    const selection = window.getSelection();
    const hasSelection = selection && !selection.isCollapsed && selection.toString().trim().length > 0;
    sendResponse({ hasSelection: hasSelection });
    return true;
  }
});

// Initialize on load
(function init() {
  createFloatingButton();
  createSelectionModal();
})();
