// popup.js - English Study Club Popup Controller

const statusDot = document.getElementById('statusDot');
const detectCaptionsBtn = document.getElementById('detectCaptionsBtn');
const langRow = document.getElementById('langRow');
const langSelect = document.getElementById('langSelect');
const extractBtn = document.getElementById('extractBtn');
const extractProgress = document.getElementById('extractProgress');
const captionStatus = document.getElementById('captionStatus');
const selectionStatus = document.getElementById('selectionStatus');
const settingsLink = document.getElementById('settingsLink');

let captionTracks = [];

// Format local date-time: YYYY-MM-DD HH:mm:ss
function formatLocalDateTime(d) {
  const p = (n) => String(n).padStart(2, '0');
  return d.getFullYear() + '-' + p(d.getMonth() + 1) + '-' + p(d.getDate()) + ' ' + p(d.getHours()) + ':' + p(d.getMinutes()) + ':' + p(d.getSeconds());
}

// Format local file stamp: YYYYMMDD_HHmmss
function formatLocalFileStamp(d) {
  const p = (n) => String(n).padStart(2, '0');
  return d.getFullYear() + p(d.getMonth() + 1) + p(d.getDate()) + '_' + p(d.getHours()) + p(d.getMinutes()) + p(d.getSeconds());
}

// Build caption markdown file content
function buildCaptionMd(title, sourceUrl, capturedAt, langName, text) {
  return [
    '# ' + title,
    '',
    '- 来源: ' + sourceUrl,
    '- 提取时间: ' + capturedAt,
    '- 语言: ' + langName,
    '',
    text
  ].join('\n');
}

// Check Native Host connection status
async function checkConnection() {
  try {
    const response = await chrome.runtime.sendMessage({ action: 'ping' });
    if (response && response.connected) {
      statusDot.classList.remove('disconnected');
      statusDot.classList.add('connected');
      statusDot.title = 'Native Host: connected';
      return true;
    }
  } catch (e) {
    // ignore
  }
  statusDot.classList.remove('connected');
  statusDot.classList.add('disconnected');
  statusDot.title = 'Native Host: disconnected';
  return false;
}

// Show status message
function showStatus(el, message, type) {
  const msg = el.querySelector('.status-msg');
  if (msg) {
    msg.textContent = message;
  } else {
    el.textContent = message;
  }
  el.classList.remove('hidden', 'success', 'error');
  if (type) el.classList.add(type);
  el.classList.remove('hidden');
}

function hideStatus(el) {
  el.classList.add('hidden');
}

// Detect captions
detectCaptionsBtn.addEventListener('click', async () => {
  hideStatus(captionStatus);
  langRow.classList.remove('show');
  langSelect.innerHTML = '';
  captionTracks = [];

  try {
    const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
    if (!tab || !tab.url || !tab.url.includes('youtube.com')) {
      showStatus(captionStatus, '请在 YouTube 视频页面使用此功能', 'error');
      return;
    }

    const response = await chrome.tabs.sendMessage(tab.id, { action: 'detectCaptions' });

    if (response && response.success && response.tracks && response.tracks.length > 0) {
      captionTracks = response.tracks;
      captionTracks.forEach((track, index) => {
        const option = document.createElement('option');
        option.value = index;
        option.textContent = track.name + (track.autoGenerated ? ' (自动生成)' : '');
        langSelect.appendChild(option);
      });
      langRow.classList.add('show');
      showStatus(captionStatus, '检测到 ' + captionTracks.length + ' 种字幕语言', 'success');
    } else {
      showStatus(captionStatus, '未检测到字幕轨道', 'error');
    }
  } catch (err) {
    showStatus(captionStatus, '检测失败: ' + err.message, 'error');
  }
});

// Extract selected captions
extractBtn.addEventListener('click', async () => {
  const selectedIndex = parseInt(langSelect.value);
  if (isNaN(selectedIndex) || !captionTracks[selectedIndex]) return;

  hideStatus(captionStatus);
  extractProgress.classList.remove('hidden');
  extractBtn.disabled = true;
  detectCaptionsBtn.disabled = true;

  try {
    const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
    const response = await chrome.tabs.sendMessage(tab.id, {
      action: 'extractCaptions',
      track: captionTracks[selectedIndex]
    });

    if (response && response.success && response.text) {
      const connected = await checkConnection();
      const videoTitle = response.videoTitle || 'youtube_captions';
      const langCode = captionTracks[selectedIndex].code;
      const langName = captionTracks[selectedIndex].name || langCode;
      const sourceUrl = response.url || (tab ? tab.url : '');
      const capturedAt = response.capturedAt || formatLocalDateTime(new Date());
      const filename = 'video_' + formatLocalFileStamp(new Date()) + '.md';
      const path = 'browser-captures/' + filename;
      const content = buildCaptionMd(videoTitle, sourceUrl, capturedAt, langName, response.text);

      if (connected) {
        try {
          await chrome.runtime.sendMessage({
            action: 'write',
            path: path,
            content: content
          });
          showStatus(captionStatus, '字幕已保存到: ' + path, 'success');
        } catch (writeErr) {
          downloadFallback(filename, content);
          showStatus(captionStatus, 'Native Host 写入失败，已通过浏览器下载', 'error');
        }
      } else {
        downloadFallback(filename, content);
        showStatus(captionStatus, 'Native Host 未连接，已通过浏览器下载', 'success');
      }
    } else {
      showStatus(captionStatus, '提取字幕失败: ' + (response ? response.error : '未知错误'), 'error');
    }
  } catch (err) {
    showStatus(captionStatus, '提取失败: ' + err.message, 'error');
  } finally {
    extractProgress.classList.add('hidden');
    extractBtn.disabled = false;
    detectCaptionsBtn.disabled = false;
  }
});

// Fallback download
function downloadFallback(filename, content) {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  chrome.downloads.download({
    url: url,
    filename: filename,
    saveAs: true
  }).catch(() => {
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
  });
}

// Settings link
settingsLink.addEventListener('click', () => {
  chrome.runtime.openOptionsPage ? chrome.runtime.openOptionsPage() : chrome.tabs.create({ url: 'settings.html' });
});

// Text selection status
async function updateSelectionStatus() {
  try {
    const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
    const response = await chrome.tabs.sendMessage(tab.id, { action: 'getSelectionStatus' });
    if (response && response.hasSelection) {
      selectionStatus.textContent = '已选中文本，请点击浮动按钮保存';
      selectionStatus.style.color = 'var(--success)';
    } else {
      selectionStatus.textContent = '请在网页上选中文本后保存';
      selectionStatus.style.color = 'var(--text-secondary)';
    }
  } catch (e) {
    selectionStatus.textContent = '请在网页上选中文本后保存';
    selectionStatus.style.color = 'var(--text-secondary)';
  }
}

// Initialize
document.addEventListener('DOMContentLoaded', async () => {
  await checkConnection();
  await updateSelectionStatus();
});