/* 一次性脚本：把 data/vocab_library.json 生成 data/vocab_library.data.js
   供 file:// 等无 fetch 环境下动态加载（VocabLibrary.load 的降级通道） */
const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const src = path.join(root, 'data', 'vocab_library.json');
const out = path.join(root, 'data', 'vocab_library.data.js');

const raw = fs.readFileSync(src, 'utf8');
const data = JSON.parse(raw); // 校验 JSON 合法
const js = '/* auto-generated by .tmp-build/gen_vocab_data_js.js — 勿手改 */\n'
  + '(function (g) { g.__VOCAB_LIBRARY_DATA__ = ' + JSON.stringify(data) + '; })(window);\n';
fs.writeFileSync(out, js, 'utf8');
console.log('OK generated', out, '(', (js.length / 1024).toFixed(1), 'KB ) levels=', data.levels.length);
